# Generated by Django 3.0.8 on 2020-07-03 12:56

from django.db import migrations, models
import recipe.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_recipe_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to=recipe.models.generate_recipe_image_path),
        ),
    ]
